"""created subjects table

Revision ID: 9dd06a37220a
Revises: 
Create Date: 2024-05-08 10:19:59.867753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd06a37220a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('SubjectCode', sa.VARCHAR(length=10), nullable=False),
    sa.Column('SubjectName', sa.String(), nullable=False),
    sa.Column('Alias', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('SubjectCode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    # ### end Alembic commands ###
